Repository sandipan898/your-awesome-projects, pull requests merged in 2022-10, with the labels that each got.

#50 Create tictactoe.py
  tictactoe.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#51 Created Game_of_life.py
  gameoflife.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#53 Added AI project of smile detection in real time
  AI Smile Detector/README.md
  AI Smile Detector/face.xml
  AI Smile Detector/smile.py
  AI Smile Detector/smile.xml
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#56 Added script that generates sequence of primes
  primegenerator.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#59 Added Face Detection AI Project
  Real-time face detector/FaceDetector.py
  Real-time face detector/README.md
  Real-time face detector/haarcascade_frontalface_default.xml
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#57 Added face detection script
  face-detection/face_detection.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#60 Added Payment Project and Python File
  dot-animate.py
  plans/.gitkeep
  plans/index.html
  plans/style.css
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#61 Create PasswordValidator.py
  Password Validator/PasswordValidator.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#66 next-js-tailwind-starter template
  next-js-tailwind-pwa-starter/.eslintrc.json
  next-js-tailwind-pwa-starter/.gitignore
  next-js-tailwind-pwa-starter/README.md
  next-js-tailwind-pwa-starter/next.config.js
  next-js-tailwind-pwa-starter/package-lock.json
  next-js-tailwind-pwa-starter/package.json
  next-js-tailwind-pwa-starter/pages/_app.js
  next-js-tailwind-pwa-starter/pages/_document.js
  next-js-tailwind-pwa-starter/pages/api/hello.js
  next-js-tailwind-pwa-starter/pages/index.js
  next-js-tailwind-pwa-starter/postcss.config.js
  next-js-tailwind-pwa-starter/public/icon.png
  next-js-tailwind-pwa-starter/public/manifest.json
  next-js-tailwind-pwa-starter/styles/Home.module.css
  next-js-tailwind-pwa-starter/styles/globals.css
  next-js-tailwind-pwa-starter/tailwind.config.js
  next-js-tailwind-pwa-starter/yarn.lock
  next-js-tailwind-starter/.eslintrc.json
  next-js-tailwind-starter/.gitignore
  next-js-tailwind-starter/README.md
  next-js-tailwind-starter/next-js-tailwind-main/.eslintrc.json
  next-js-tailwind-starter/next-js-tailwind-main/.gitignore
  next-js-tailwind-starter/next-js-tailwind-main/README.md
  next-js-tailwind-starter/next-js-tailwind-main/next.config.js
  next-js-tailwind-starter/next-js-tailwind-main/package-lock.json
  next-js-tailwind-starter/next-js-tailwind-main/package.json
  next-js-tailwind-starter/next-js-tailwind-main/pages/_app.js
  next-js-tailwind-starter/next-js-tailwind-main/pages/api/hello.js
  next-js-tailwind-starter/next-js-tailwind-main/pages/index.js
  next-js-tailwind-starter/next-js-tailwind-main/postcss.config.js
  next-js-tailwind-starter/next-js-tailwind-main/public/favicon.ico
  next-js-tailwind-starter/next-js-tailwind-main/public/vercel.svg
  next-js-tailwind-starter/next-js-tailwind-main/styles/Home.module.css
  next-js-tailwind-starter/next-js-tailwind-main/styles/globals.css
  next-js-tailwind-starter/next-js-tailwind-main/tailwind.config.js
  next-js-tailwind-starter/next-js-tailwind-main/yarn.lock
  next-js-tailwind-starter/next.config.js
  next-js-tailwind-starter/package-lock.json
  next-js-tailwind-starter/package.json
  next-js-tailwind-starter/pages/_app.js
  next-js-tailwind-starter/pages/api/hello.js
  next-js-tailwind-starter/pages/index.js
  next-js-tailwind-starter/postcss.config.js
  next-js-tailwind-starter/public/favicon.ico
  next-js-tailwind-starter/public/vercel.svg
  next-js-tailwind-starter/styles/Home.module.css
  next-js-tailwind-starter/styles/globals.css
  next-js-tailwind-starter/tailwind.config.js
  next-js-tailwind-starter/yarn.lock
Labels: hacktoberfest-accepted

#64 BillBoard-To-Spotify
  From-BillBoard-To-Spotify-main/README.md
  From-BillBoard-To-Spotify-main/main.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#65 Added Popular Algorithms
  Algorithms/Backtracking.cpp
  Algorithms/Backtracking.exe
  Algorithms/Euclid_Algo.cpp
  Algorithms/Euclid_Algo.exe
  Algorithms/Inclusion_Exclusion.cpp
  Algorithms/Inclusion_Exclusion.exe
  Algorithms/Kadanes.cpp
  Algorithms/Kadanes.exe
  Algorithms/SOE.cpp
  Algorithms/SOE.exe
  Algorithms/Sorting/.cph/.NextGreaterElement.cpp_74ae122c2601ae88a8f1e923533769cb.prob
  Algorithms/Sorting/BubbleSort.cpp
  Algorithms/Sorting/BubbleSort.exe
  Algorithms/Sorting/InsertionSort.cpp
  Algorithms/Sorting/InsertionSort.exe
  Algorithms/Sorting/NextGreaterElement.cpp
  Algorithms/Sorting/NextGreaterElement.exe
  Algorithms/Sorting/SelectionSort.cpp
  Algorithms/Sorting/SelectionSort.exe
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#68 Create .gitignore
  Certificate-Generator/.gitignore
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#70 Adding satoshi font
  CALENDAR/index.html
  CALENDAR/style.css
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#73 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#76 Added programs on number theory
  Number Theory/.cph/.BIT_Masking.cpp_dcb98f804800179e24a6baa225eaf715.prob
  Number Theory/BIT_Masking.cpp
  Number Theory/Basics.cpp
  Number Theory/Basics.exe
  Number Theory/BinaryExp.cpp
  Number Theory/BinaryExp.exe
  Number Theory/GCD_LCM.cpp
  Number Theory/GCD_LCM.exe
  Number Theory/SubsetWithBits.cpp
  Number Theory/TXOR.cpp
  Number Theory/TXOR.exe
  Number Theory/Tricks.cpp
  Number Theory/Tricks.exe
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#75 Added Image Converter
  Python Mini Projects/imageconverter.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#77 Added Word Dictionary Project
  Word Dictionary/README.md
  Word Dictionary/package-lock.json
  Word Dictionary/package.json
  Word Dictionary/public/apple-touch-icon.png
  Word Dictionary/public/favicon-16x16.png
  Word Dictionary/public/favicon-32x32.png
  Word Dictionary/public/favicon.ico
  Word Dictionary/public/index.html
  Word Dictionary/public/logo.png
  Word Dictionary/public/logo192.png
  Word Dictionary/public/logo256.png
  Word Dictionary/public/logo384.png
  Word Dictionary/public/logo512.png
  Word Dictionary/public/manifest.json
  Word Dictionary/public/maskable.png
  Word Dictionary/public/robots.txt
  Word Dictionary/src/.gitignore
  Word Dictionary/src/App.css
  Word Dictionary/src/App.js
  Word Dictionary/src/components/Definations/Definations.css
  Word Dictionary/src/components/Definations/Definations.js
  Word Dictionary/src/components/Header/Header.css
  Word Dictionary/src/components/Header/Header.js
  Word Dictionary/src/data/Categories.js
  Word Dictionary/src/index.css
  Word Dictionary/src/index.js
  Word Dictionary/src/service-worker.js
  Word Dictionary/src/serviceWorkerRegistration.js
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#78 Add BalloonShooter project
  BalloonShooter/BalloonShooter.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#81 restaurant management system
  Python Mini Projects/restaurant.ipynb
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#79 Added Portfolio Site
  Flexbox-Tutorial/index.html
  Flexbox-Tutorial/script.js
  Flexbox-Tutorial/style.css
  Portfolio-Site/README.md
  Portfolio-Site/package-lock.json
  Portfolio-Site/package.json
  Portfolio-Site/postcss.config.js
  Portfolio-Site/public/apple-touch-icon.png
  Portfolio-Site/public/favicon-16x16.png
  Portfolio-Site/public/favicon-32x32.png
  Portfolio-Site/public/favicon.ico
  Portfolio-Site/public/index.html
  Portfolio-Site/public/logo192.png
  Portfolio-Site/public/logo512.png
  Portfolio-Site/public/manifest.json
  Portfolio-Site/public/robots.txt
  Portfolio-Site/src/App.js
  Portfolio-Site/src/components/About.js
  Portfolio-Site/src/components/Card.js
  Portfolio-Site/src/components/Contact.js
  Portfolio-Site/src/components/Footer.js
  Portfolio-Site/src/components/Projects.js
  Portfolio-Site/src/components/Skills.js
  Portfolio-Site/src/components/images/notes3.png
  Portfolio-Site/src/components/images/profile.jpg
  Portfolio-Site/src/components/images/profile.png
  Portfolio-Site/src/components/images/task.png
  Portfolio-Site/src/components/images/weatherapp.png
  Portfolio-Site/src/components/images/wordweb4.png
  Portfolio-Site/src/index.css
  Portfolio-Site/src/index.js
  Portfolio-Site/style.css
  Portfolio-Site/tailwind.config.js
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#84 Added React-Real-Estate
  Real-Estate-React/README.md
  Real-Estate-React/package-lock.json
  Real-Estate-React/package.json
  Real-Estate-React/postcss.config.js
  Real-Estate-React/public/966.jpg
  Real-Estate-React/public/favicon.ico
  Real-Estate-React/public/index.html
  Real-Estate-React/public/logo192.png
  Real-Estate-React/public/logo512.png
  Real-Estate-React/public/manifest.json
  Real-Estate-React/public/robots.txt
  Real-Estate-React/src/App.css
  Real-Estate-React/src/App.js
  Real-Estate-React/src/assets/7300.jpg
  Real-Estate-React/src/assets/966.jpg
  Real-Estate-React/src/assets/area-icon.png
  Real-Estate-React/src/assets/bathroom-icon.png
  Real-Estate-React/src/assets/bed-icon.png
  Real-Estate-React/src/assets/favorate-icon.png
  Real-Estate-React/src/assets/hamburger.png
  Real-Estate-React/src/components/Header/Header.js
  Real-Estate-React/src/components/Header/Header.module.css
  Real-Estate-React/src/components/HomePage/Homepage.js
  Real-Estate-React/src/components/HomePage/Homepage.module.css
  Real-Estate-React/src/components/card/Card.js
  Real-Estate-React/src/components/card/Card.module.css
  Real-Estate-React/src/dummy-data/dummy-data-houses.js
  Real-Estate-React/src/index.css
  Real-Estate-React/src/index.js
  Real-Estate-React/tailwind.config.js
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#82 Created musicplayer.py
  Python Mini Projects/musicplayer.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#83 ADDED TO-DO List
  To-Do-List-By-GarvLuthra24/README.md
  To-Do-List-By-GarvLuthra24/index.html
  To-Do-List-By-GarvLuthra24/script.js
  To-Do-List-By-GarvLuthra24/style.css
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#87 Secret Sharing
  Secrets-Sharing/README.md
  Secrets-Sharing/app.js
  Secrets-Sharing/package-lock.json
  Secrets-Sharing/package.json
  Secrets-Sharing/public/css/bootstrap-social.css
  Secrets-Sharing/public/css/styles.css
  Secrets-Sharing/public/secret.png
  Secrets-Sharing/views/home.ejs
  Secrets-Sharing/views/login.ejs
  Secrets-Sharing/views/partials/footer.ejs
  Secrets-Sharing/views/partials/header.ejs
  Secrets-Sharing/views/register.ejs
  Secrets-Sharing/views/secrets.ejs
  Secrets-Sharing/views/submit.ejs
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#89 TODO using PERN Stack
  TODO_PERN/.gitignore
  TODO_PERN/README.md
  TODO_PERN/client/README.md
  TODO_PERN/client/package.json
  TODO_PERN/client/public/favicon.ico
  TODO_PERN/client/public/index.html
  TODO_PERN/client/public/logo192.png
  TODO_PERN/client/public/logo512.png
  TODO_PERN/client/public/manifest.json
  TODO_PERN/client/public/robots.txt
  TODO_PERN/client/src/App.css
  TODO_PERN/client/src/App.js
  TODO_PERN/client/src/App.test.js
  TODO_PERN/client/src/api/api.js
  TODO_PERN/client/src/components/MainContainer.js
  TODO_PERN/client/src/components/NavBar.jsx
  TODO_PERN/client/src/components/TodoForm.jsx
  TODO_PERN/client/src/components/TodoTable.jsx
  TODO_PERN/client/src/index.css
  TODO_PERN/client/src/index.js
  TODO_PERN/client/src/logo.svg
  TODO_PERN/client/src/redux/Store.js
  TODO_PERN/client/src/redux/actionTypes/todoTypes.js
  TODO_PERN/client/src/redux/actions/todoActions.js
  TODO_PERN/client/src/redux/reducers/index.js
  TODO_PERN/client/src/redux/reducers/todos.js
  TODO_PERN/client/src/reportWebVitals.js
  TODO_PERN/client/src/setupTests.js
  TODO_PERN/server/config/db.config.js
  TODO_PERN/server/database.sql
  TODO_PERN/server/db.js
  TODO_PERN/server/index.js
  TODO_PERN/server/models/Todo.js
  TODO_PERN/server/models/index.js
  TODO_PERN/server/package.json
  TODO_PERN/server/routes/todo.js
  TODO_PERN/server/routes/todoRaw.js
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#91 Quote Generator
  Quote-Generator/README.md
  Quote-Generator/bulb.jpg
  Quote-Generator/quote.html
  Quote-Generator/quote.js
  Quote-Generator/thought.jpg
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#94 Typing Speed Calculator
  type.java
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#96 Number Guessing Game in Java
  num_guess.java
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#98 Greedy algorithms in C++
  Greedy Algorithms/Dijkstra.cpp
  Greedy Algorithms/Knapsack.cpp
  Greedy Algorithms/Kruskals Minimum Spanning Tree.cpp
  Greedy Algorithms/Prims Minimum Spanning Tree.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#100 Added jupyter file of Ai number detection
  Ai based handwritten number detection/handwritten number detection.ipynb
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#105 Adding Medium-Clone responsive frontend website
  medium-clone/1.jpg
  medium-clone/2.jpg
  medium-clone/3.jpg
  medium-clone/4.jpg
  medium-clone/5.jpg
  medium-clone/index.html
  medium-clone/style.css
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#104 Added Raspberry Pi project which detects input on gpio pin
  Raspberry Pi input detection gpio/input.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#103 Java Implementation of Insertion Sort
  Insertion Sort
  password.java
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#102 Smart Contracts for Tokens in Solidity
  Generate-Tokens/Fungible-Token-Contract.sol
  Generate-Tokens/Non-Fungible-Token-Contract.sol
  Generate-Tokens/README.md
Labels: hacktoberfest-accepted, hacktoberfest2021, hacktoberfest

#106 Java Program to Calculate PI
  pi.java
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#109 added python pokemon website Imagewebscrapper using cv2
  Python Mini Projects/Pokemon_imagewebscarpper_cv2/README.md
  Python Mini Projects/Pokemon_imagewebscarpper_cv2/images/001 .png
  Python Mini Projects/Pokemon_imagewebscarpper_cv2/images/002 .png
  Python Mini Projects/Pokemon_imagewebscarpper_cv2/images/003 .png
  Python Mini Projects/Pokemon_imagewebscarpper_cv2/images/004 .png
  Python Mini Projects/Pokemon_imagewebscarpper_cv2/images/005 .png
  Python Mini Projects/Pokemon_imagewebscarpper_cv2/readme.txt
  Python Mini Projects/Pokemon_imagewebscarpper_cv2/scrape.py
  Python Mini Projects/Pokemon_imagewebscarpper_cv2/webimage.png
  Python Mini Projects/Pokemon_imagewebscarpper_cv2/webimage1.PNG
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#111 Added programs and notes on bit manipulation
  BIT manipulation/Bit_Chlng_1.cpp
  BIT manipulation/Bit_Chlng_1.exe
  BIT manipulation/Bits_Adv.cpp
  BIT manipulation/Bits_Adv.exe
  BIT manipulation/bit_basics.cpp
  BIT manipulation/bit_basics.exe
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#112 rock scissors paper game
  rock paper scissors/rps.css
  rock paper scissors/rps.html
  rock paper scissors/rps.js
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#114 Digital clock page React JS
  Digital-clock/.gitignore
  Digital-clock/package-lock.json
  Digital-clock/package.json
  Digital-clock/public/bootstrap.min.css
  Digital-clock/public/favicon.ico
  Digital-clock/public/index.html
  Digital-clock/public/logo192.png
  Digital-clock/public/logo512.png
  Digital-clock/public/manifest.json
  Digital-clock/public/robots.txt
  Digital-clock/src/App.css
  Digital-clock/src/App.js
  Digital-clock/src/App.test.js
  Digital-clock/src/Clock/Clock.css
  Digital-clock/src/Clock/Clock.js
  Digital-clock/src/index.css
  Digital-clock/src/index.js
  Digital-clock/src/logo.svg
  Digital-clock/src/reportWebVitals.js
  Digital-clock/src/setupTests.js
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#113 Added programs on Array operations using C++
  Arrays/MatrixMultiply.cpp
  Arrays/MatrixSearch.cpp
  Arrays/MaxRepeat.cpp
  Arrays/MaxRepeat.exe
  Arrays/PairSum.cpp
  Arrays/Pointers.cpp
  Arrays/Spiral.cpp
  Arrays/Transpose.cpp
  Recursion/Advanced.cpp
  Recursion/Advanced.exe
  Recursion/Basics.cpp
  Recursion/Basics.exe
  Recursion/Medium.cpp
  Recursion/Medium.exe
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#115 Create morse_code.c
  Morse Code/morse_code.c
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#121 Contributed with 8-queen problem's solution with python
  Spell-Checker.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#123 Added an implementation of Arrays
  MatrixMultiply.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#125 Added a program related to pointers
  Pointers.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#126 Add ML project: churn modelling
  README.md
  churn_modelling/.gitignore
  churn_modelling/Churn Modelling.ipynb
  churn_modelling/Churn_Modelling.csv
  churn_modelling/LICENSE
  churn_modelling/Procfile
  churn_modelling/README.md
  churn_modelling/bank_test_model.ipynb
  churn_modelling/model_v0.bin
  churn_modelling/notes during training.txt
  churn_modelling/predict.py
  churn_modelling/requirements.txt
  churn_modelling/runtime.txt
  churn_modelling/static/style.css
  churn_modelling/templates/index.html
  churn_modelling/train.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#127 Update index.html
  quotes/index.html
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#129 shooting game scratch
  shooting game scratch/shooting game scratch.sb3
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#130 Create PasswordValidator.py
  PasswordValidator.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#131 Create QuickSort.py
  Algorithms/QuickSort.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#133 Array Reverse
  Arrays/ArrayReverse.cpp
  Story Generator/StoryGenerator.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#134 long-pressed-name
  Arrays/long-pressed-name
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022
